name: Build and deploy ASP.Net Core app to Azure Web App - productTrialMasterDotnet

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{github.workspace}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp  

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4 
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp 

      - name: Set environment variables
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
      
      - name: Add secrets to Azure App Service
        uses: azure/appservice-settings@v1
        with:
          app-name: 'productTrialMasterDotnet'
          app-settings-json: |
            {
              "DB_USER": "${{ secrets.DB_USER }}",
              "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
              "PRIVATE_KEY": "${{ secrets.PRIVATE_KEY }}"
            }
            
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'productTrialMasterDotnet'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB89B14C639449358C272EE4D518BB6A }}
          package: ${{github.workspace}}/myapp
